on:
    push
jobs:
    build_job_1:
      runs-on: ubuntu-latest
      steps:
      - name: Install cowsay program
        run: sudo apt-get install cowsay -y

      - name: Excute cowsay CMD
        run: cowsay -f dragon "Run for cover, i am a DRAGON ....RAWR " >> dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-artifact
          path: dragon.txt
      
      - name: sleep for 30 seconds
        run: sleep 30

    test_job_2:
      needs: build_job_1
      runs-on: ubuntu-latest
      steps:
      - name: Upload Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact


      - name: Test file Exists
        run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Upload Dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon-artifact
        - name: Read file
          run: act dragon.txt

        - name: Deploying
          run: echo "Deploying......."
